=begin
#RIXL API

#**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

The version of the OpenAPI document: 2.0
Contact: support@rixl.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ImagesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ImagesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ImagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImagesApi' do
    it 'should create an instance of ImagesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ImagesApi)
    end
  end

  # unit tests for delete_images_image_id
  # Delete image
  # delete an image by marking it as deleted
  # @param image_id Image ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_images_image_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_images
  # List images for a project
  # Retrieve all images for a specific project, with pagination and sorting.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of items to return in a single request. &lt;br&gt; **Default:** &#x60;25&#x60;
  # @option opts [Integer] :offset Starting point of the result set. &lt;br&gt;To get page 2 with a limit of 25, set &#x60;offset&#x60; to &#x60;25&#x60;. &lt;br&gt; **Default:** &#x60;0&#x60;
  # @option opts [String] :sort Field to sort by (created_at, name, size, updated_at)
  # @option opts [String] :order Sort order (asc, desc)
  # @return [PaginationPaginatedResponseImage]
  describe 'get_images test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_images_image_id
  # Get image
  # Retrieve an image by its ID for a specific project.
  # @param image_id Image ID
  # @param [Hash] opts the optional parameters
  # @return [Image]
  describe 'get_images_image_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_images_upload_complete
  # Upload: Mark as complete
  # Complete the upload process and create the image record using API key authentication
  # @param request Upload completion request
  # @param [Hash] opts the optional parameters
  # @return [Image]
  describe 'post_images_upload_complete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_images_upload_init
  # Upload: Init
  # Initialize a presigned URL upload for an image file using API key authentication
  # @param request Upload initialization request
  # @param [Hash] opts the optional parameters
  # @return [InternalImagesHandlerInitResponse]
  describe 'post_images_upload_init test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
