=begin
#RIXL API

#**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

The version of the OpenAPI document: 2.0
Contact: support@rixl.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::FeedsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FeedsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::FeedsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FeedsApi' do
    it 'should create an instance of FeedsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::FeedsApi)
    end
  end

  # unit tests for get_feeds_feed_id
  # List posts in a feed
  # Retrieve posts in a feed, with pagination.
  # @param feed_id Feed ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of items to return in a single request. &lt;br&gt; **Default:** &#x60;25&#x60;
  # @option opts [Integer] :offset Starting point of the result set. &lt;br&gt;To get page 2 with a limit of 25, set &#x60;offset&#x60; to &#x60;25&#x60;. &lt;br&gt; **Default:** &#x60;0&#x60;
  # @return [PaginationPaginatedResponsePost]
  describe 'get_feeds_feed_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_feeds_feed_id_creators_creator_id
  # List posts by creator
  # Retrieve posts in a feed by a specific creator, with pagination.
  # @param feed_id Feed ID
  # @param creator_id Creator ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of items to return in a single request. &lt;br&gt; **Default:** &#x60;25&#x60;
  # @option opts [Integer] :offset Starting point of the result set. &lt;br&gt;To get page 2 with a limit of 25, set &#x60;offset&#x60; to &#x60;25&#x60;. &lt;br&gt; **Default:** &#x60;0&#x60;
  # @return [PaginationPaginatedResponsePost]
  describe 'get_feeds_feed_id_creators_creator_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_feeds_feed_id_post_id
  # Get a post
  # Retrieve a post from feed by its ID
  # @param feed_id Feed ID
  # @param post_id Post ID
  # @param [Hash] opts the optional parameters
  # @return [Post]
  describe 'get_feeds_feed_id_post_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
