=begin
#RIXL API

#**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

The version of the OpenAPI document: 2.0
Contact: support@rixl.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module RixlVideosSdk
  class FileStatus
    FileStatusUploading = "uploading".freeze
    FileStatusUploaded = "uploaded".freeze
    FileStatusProcessing = "processing".freeze
    FileStatusPreparing = "preparing".freeze
    FileStatusReady = "ready".freeze
    FileStatusError = "error".freeze

    def self.all_vars
      @all_vars ||= [FileStatusUploading, FileStatusUploaded, FileStatusProcessing, FileStatusPreparing, FileStatusReady, FileStatusError].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FileStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FileStatus"
    end
  end
end
