=begin
#RIXL API

#**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

The version of the OpenAPI document: 2.0
Contact: support@rixl.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::VideosApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VideosApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::VideosApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VideosApi' do
    it 'should create an instance of VideosApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::VideosApi)
    end
  end

  # unit tests for videos_get
  # List videos for a project
  # Retrieve all videos for a specific project, with pagination and sorting.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Maximum number of items to return in a single request. &lt;br&gt; **Default:** &#x60;25&#x60;
  # @option opts [Integer] :offset Starting point of the result set. &lt;br&gt;To get page 2 with a limit of 25, set &#x60;offset&#x60; to &#x60;25&#x60;. &lt;br&gt; **Default:** &#x60;0&#x60;
  # @option opts [String] :sort Field to sort by (created_at, name, size, updated_at, duration)
  # @option opts [String] :order Sort order (asc, desc)
  # @return [PaginationPaginatedResponseVideo]
  describe 'videos_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_languages_get
  # List available subtitle languages
  # Get list of supported languages for subtitles
  # @param [Hash] opts the optional parameters
  # @return [Array<InternalVideosHandlerSubtitlesLanguageResponse>]
  describe 'videos_languages_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_upload_complete_post
  # Upload: Mark as complete
  # Mark a video upload as complete after successful upload to storage using API key authentication
  # @param videos_upload_complete_post_request Video upload completion request
  # @param [Hash] opts the optional parameters
  # @return [Video]
  describe 'videos_upload_complete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_upload_init_post
  # Upload: Init
  # Initialize a video upload and get presigned URLs for video and poster using API key authentication
  # @param videos_upload_init_post_request Video upload initialization request
  # @param [Hash] opts the optional parameters
  # @return [GithubComQeeqezApiInternalVideosHandlerUploadInitResponse]
  describe 'videos_upload_init_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_audio_tracks_delete
  # Delete all audio tracks
  # Remove all additional audio tracks from a video using API key authentication
  # @param video_id Video ID
  # @param [Hash] opts the optional parameters
  # @return [AudioTrackDelete]
  describe 'videos_video_id_audio_tracks_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_audio_tracks_lang_code_delete
  # Delete audio track by language
  # Remove an audio track for a specific language using API key authentication
  # @param video_id Video ID
  # @param lang_code Language Code (BCP 47)
  # @param [Hash] opts the optional parameters
  # @return [AudioTrackDelete]
  describe 'videos_video_id_audio_tracks_lang_code_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_audio_tracks_lang_code_put
  # Upsert video audio track
  # Add or replace an audio track for a specific language using API key authentication
  # @param video_id Video ID
  # @param lang_code Language Code (BCP 47)
  # @param [Hash] opts the optional parameters
  # @return [AudioTrack]
  describe 'videos_video_id_audio_tracks_lang_code_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_audio_tracks_post
  # Bulk upsert video audio tracks
  # Replace all audio tracks with the provided ones using API key authentication
  # @param video_id Video ID
  # @param [Hash] opts the optional parameters
  # @return [Array<AudioTrack>]
  describe 'videos_video_id_audio_tracks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_audio_tracks_track_id_delete
  # Delete audio track
  # Remove an additional audio track from a video using API key authentication
  # @param video_id Video ID
  # @param track_id Audio Track ID
  # @param [Hash] opts the optional parameters
  # @return [AudioTrackDelete]
  describe 'videos_video_id_audio_tracks_track_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_chapters_delete
  # Delete video chapters
  # Remove all chapters from a video using API key authentication
  # @param video_id Video ID
  # @param [Hash] opts the optional parameters
  # @return [UpdateChaptersResponse]
  describe 'videos_video_id_chapters_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_chapters_put
  # Update video chapters
  # Replace all chapters for a video (atomic PUT operation) using API key authentication
  # @param video_id Video ID
  # @param videos_video_id_chapters_put_request Chapters array
  # @param [Hash] opts the optional parameters
  # @return [UpdateChaptersResponse]
  describe 'videos_video_id_chapters_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_delete_delete
  # Delete video
  # Delete a video by its ID within a project
  # @param video_id Video ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'videos_video_id_delete_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_get
  # Get a video
  # Retrieve a video by its ID for a specific project.
  # @param video_id Video ID
  # @param [Hash] opts the optional parameters
  # @return [Video]
  describe 'videos_video_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_subtitles_delete
  # Delete all subtitles
  # Remove all subtitles from a video using API key authentication
  # @param video_id Video ID
  # @param [Hash] opts the optional parameters
  # @return [SubtitleDelete]
  describe 'videos_video_id_subtitles_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_subtitles_lang_code_delete
  # Delete subtitle by language
  # Remove a subtitle for a specific language using API key authentication
  # @param video_id Video ID
  # @param lang_code Language Code (BCP 47)
  # @param [Hash] opts the optional parameters
  # @return [SubtitleDelete]
  describe 'videos_video_id_subtitles_lang_code_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_subtitles_lang_code_put
  # Upsert video subtitle
  # Add or replace a subtitle for a specific language using API key authentication
  # @param video_id Video ID
  # @param lang_code Language Code (BCP 47)
  # @param [Hash] opts the optional parameters
  # @return [Subtitle]
  describe 'videos_video_id_subtitles_lang_code_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_subtitles_post
  # Bulk upsert video subtitles
  # Replace all subtitles with the provided ones using API key authentication
  # @param video_id Video ID
  # @param [Hash] opts the optional parameters
  # @return [Array<Subtitle>]
  describe 'videos_video_id_subtitles_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_subtitles_subtitle_id_delete
  # Delete subtitle
  # Remove a subtitle from a video using API key authentication
  # @param video_id Video ID
  # @param subtitle_id Subtitle ID
  # @param [Hash] opts the optional parameters
  # @return [SubtitleDelete]
  describe 'videos_video_id_subtitles_subtitle_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for videos_video_id_thumbnail_put
  # Update video thumbnail
  # Update the thumbnail image for an existing video using API key authentication
  # @param video_id Video ID
  # @param [Hash] opts the optional parameters
  # @return [Video]
  describe 'videos_video_id_thumbnail_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
