=begin
#RIXL API

#**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

The version of the OpenAPI document: 2.0
Contact: support@rixl.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PostType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PostType do
  #let(:instance) { OpenapiClient::PostType.new }

  describe 'test an instance of PostType' do
    it 'should create an instance of PostType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PostType)
    end
  end

end
