=begin
#RIXL API

#**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

The version of the OpenAPI document: 2.0
Contact: support@rixl.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/api_model_base'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/audio_track'
require 'openapi_client/models/audio_track_delete'
require 'openapi_client/models/chapter'
require 'openapi_client/models/file'
require 'openapi_client/models/file_status'
require 'openapi_client/models/github_com_qeeqez_api_db_sqlc_plan_type'
require 'openapi_client/models/github_com_qeeqez_api_db_sqlc_video_quality'
require 'openapi_client/models/github_com_qeeqez_api_internal_errors_error_response'
require 'openapi_client/models/github_com_qeeqez_api_internal_videos_handler_upload_complete_request'
require 'openapi_client/models/github_com_qeeqez_api_internal_videos_handler_upload_init_response'
require 'openapi_client/models/github_com_qeeqez_api_internal_videos_types_chapter_input'
require 'openapi_client/models/image'
require 'openapi_client/models/internal_videos_handler_subtitles_language_response'
require 'openapi_client/models/pagination_paginated_response_video'
require 'openapi_client/models/pagination_pagination'
require 'openapi_client/models/subtitle'
require 'openapi_client/models/subtitle_delete'
require 'openapi_client/models/update_chapters_request'
require 'openapi_client/models/update_chapters_response'
require 'openapi_client/models/video'
require 'openapi_client/models/video_upload_init_request'

# APIs
require 'openapi_client/api/videos_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
